### ISSUE TITLE
Test button does not reliably work

### ISSUE THREAD

**Issue by vanstoner** [xebialabs-community/xlr-servicenow-plugin#23]
Not all customers are licensed for performance analytics.  As a consequence the Test button which executes the following code in the ServiceNowClient.py might fail with an authorisation error

<pre>get_scorecard</pre>

**Comment by jdewinne** [comment]
Fixed in [v4.1.10](https://github.com/xebialabs-community/xlr-servicenow-plugin/releases/tag/v4.1.10)
