### ISSUE TITLE
sn icon is broken

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xlr-servicenow-plugin#26]
XL Release 7.0.2
plugin version v4.1.12

The SN icon is broken. 

![grabberraster 0098](https://user-images.githubusercontent.com/7237078/36264869-38baaafc-126e-11e8-92e4-bd8d059cf615.jpg)

**Comment by jdewinne** [comment]
As a temporary workaround you might add the icon under `ext`

**Comment by jdewinne** [comment]
I've fixed it on the master branch.

**Comment by ltutar** [comment]
Any plans to create a new release?

**Comment by jdewinne** [comment]
Done. See [v4.1.13](https://github.com/xebialabs-community/xlr-servicenow-plugin/releases/tag/v4.1.13)
