### ISSUE TITLE
Notifying Service Now after aborting a release

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xlr-servicenow-plugin#29]
This problem is not specific to Service Now. But also becomes a problem in our project. When an XLR user aborts the XLR release, Service Now does not get a notification and the Service Now change stays open. This way, the XLR and Service Now are not in sync. 

A solution like start a process when the abort button is clicked, would be nice.

---
A release can be manually aborted at any point, at which point it will be in the ‘aborted’ state. 
from 
https://docs.xebialabs.com/xl-release/concept/release-life-cycle.html

**Comment by jdewinne** [comment]
Will close, as this is not ServiceNow plugin related.
